name: C++ unit

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with: 
        submodules: true
    - name: Build CMake
      run: |
        cd luhncpp && cd build
        cmake .. -DCMAKE_BUILD_TYPE=Debug -G "Unix Makefiles"
    - name: Build and run unit tests
      run: |
        cd luhncpp && cd build
        make luhncpp_test
        ./bin/luhncpp_test